version: '1.0'

services:
  spring:
    build:
      context: .
      dockerfile: ./docker/docker-compose.yml
    container_name: spring
    ports:
      "8080:8080"
    networks:
      - dain-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - spring
    networks:
      - dain-network

networks:
  dain-network:
    driver: bridge