name: Dain-Review CI/CD Script

on:
  push:
    branches:
      - release
      - feature/cicd

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 CheckOut
        uses: actions/checkout@v2

      - name: Docker 빌드
        uses: docker/setup-buildx-action@v1

      - name: Github Registry 로그인
        env:
          CR_PAT: ${{ secrets.DAIN_REVIEW_TOKEN }}
        run: echo $CR_PAT | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: MySQL Docker 빌드
        env:
          IMAGE_NAME: mysql
          IMAGE_TAG: latest
        run: |
          docker build -t ghcr.io/${{ github.repository }}/$IMAGE_NAME:$IMAGE_TAG -f docker/Dockerfile-database .

      - name: Docker Image Push
        env:
          IMAGE_NAME: mysql
          IMAGE_TAG: latest
        run: |
          docker push ghcr.io/${{ github.repository }}/$IMAGE_NAME:$IMAGE_TAG
